spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chatapp?sslmode=disable
    username: chatuser
    password: chatpass
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 3MB

  jwt:
    secret: the-super-secret-key-that-is-at-least-32-characters-long
    expiration: 3600000

  logging:
    level:
      root: INFO
      de.sophieherstein.chat_app_backend: DEBUG
      org.springframework.security: INFO
      org.hibernate.SQL: WARN